version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/enbysocial
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - enbysocial-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enbysocial
    ports:
      - "5432:5432"
    networks:
      - enbysocial-network

volumes:
  postgres_data:

networks:
  enbysocial-network:
    driver: bridge
